# Generated by Django 3.2.9 on 2021-11-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksAuthor',
            new_name='Books_Author',
        ),
    ]
